// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOWChAogf3hqlzWyHlplGC3KrYLmCnxn4',
    appId: '1:860422104667:web:10d2558e9fe5e67744817e',
    messagingSenderId: '860422104667',
    projectId: 'esacc-2fcb0',
    authDomain: 'esacc-2fcb0.firebaseapp.com',
    storageBucket: 'esacc-2fcb0.appspot.com',
    measurementId: 'G-7LWVFQW9XC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9lmPhSuwf9JZfohWh3QHgx35cMqWqDU4',
    appId: '1:860422104667:android:36b404dc60564da244817e',
    messagingSenderId: '860422104667',
    projectId: 'esacc-2fcb0',
    storageBucket: 'esacc-2fcb0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9VQj_e0_iIZ9FCOsEZ01Wky_JFMni56g',
    appId: '1:860422104667:ios:24b877aadcbbc15c44817e',
    messagingSenderId: '860422104667',
    projectId: 'esacc-2fcb0',
    storageBucket: 'esacc-2fcb0.appspot.com',
    iosBundleId: 'com.example.easaccWebView',
  );
}
